# Generated by Django 3.0.7 on 2020-06-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercalendarevent',
            name='no_physical_location',
            field=models.BooleanField(default=False),
        ),
    ]
