- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
  - id: trailing-whitespace
  - id: debug-statements
  - id: check-merge-conflict
    exclude: "migrations/*"

- repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
  sha: v0.0.2
  hooks:
  - id: pydocstyle
    exclude: "migrations/*"
    args: ['--ignore=D100,D105,D203']

- repo: git://github.com/pricematch/pricematch-pre-commit-hooks
  sha: 82b0c142b363547cc873bc6581fa3074087a37d2
  hooks:
  - id: do_not_commit

- repo: https://github.com/asottile/pyupgrade
  rev: 032bd2fd260e065c69079678050678b31d4736cb
  hooks:
  - id: pyupgrade
    exclude:
      migrations/

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: ffbd448645bad2e7ca13f96fca5830058d27ccd5
  hooks:
  - id: forbid-crlf

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    exclude:
      migrations/
