# Generated by Django 2.2.8 on 2019-12-09 21:52

import common.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('common', '__first__'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('og_type', models.CharField(choices=[('article', 'Article'), ('website', 'Website'), ('book', 'Book'), ('video', 'Video'), ('profile', 'Profile')], default='website', help_text='See Object Types: https://developers.facebook.com/docs/reference/opengraph/', max_length=127, verbose_name='OG Page Type')),
                ('body', wagtail.core.fields.StreamField([('banner_image', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('internal_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False)), ('alt_text', wagtail.core.blocks.CharBlock(max_length=255, required=False))])), ('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock()), ('photo_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')])), ('caption', wagtail.core.blocks.CharBlock(max_length=255)), ('caption_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('tl', 'Left'), ('tr', 'Right'), ('tc', 'Center')]))])), ('h1', common.blocks.HeaderH1(classname='full title')), ('subhead', common.blocks.Subhead(classname='full title')), ('block_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(classname='full', max_length=255, required=True))])), ('call_to_action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('cta_copy', wagtail.core.blocks.CharBlock(max_length=255)), ('button_title', wagtail.core.blocks.CharBlock(max_length=255)), ('button_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_external_link', wagtail.core.blocks.URLBlock(required=False))])), ('small_call_to_action', wagtail.core.blocks.StructBlock([('button_copy', wagtail.core.blocks.CharBlock(max_length=32)), ('button_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_external_link', wagtail.core.blocks.URLBlock(required=False)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('tl', 'Left'), ('tr', 'Right'), ('tc', 'Center')]))])), ('embed_code', wagtail.core.blocks.StructBlock([('embed_code', wagtail.core.blocks.TextBlock(required=True))]))])),
                ('fundraising_snippet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.EmbedCodeSnippet')),
                ('share_image', models.ForeignKey(blank=True, help_text='Should be larger than 1200 x 630px\n See https://developers.facebook.com/docs/sharing/best-practices#images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Share Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
